name: Tests

on:
   push:
      branches:
         - main

jobs:
   test:
      runs-on: ununtu-latest

      steps:
         - name: Checkout repo
           uses: actions/checkout@v4

         - name: Jest tests
           id: jest-tests
           uses: classroom-resources/autograding-command-grader@v1
           with:
              test-name: Jest tests
              setup-command: npm install jest;npm install
              command: npm test
              timeout: 3
