name: Tests

on:
   push:
      branches:
         - main

jobs:
  test:
    runs-on: ununtu-latest

    steps:
      - name Checkout repo
        uses: actions/checkout@v2

      - name Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 22.11.0

      - name Install deps
        run: npm install

      - name: Run Jest
        run: npx jest